### ISSUE TITLE
Broken display on windows 10

### ISSUE THREAD

**Issue by twiecki** [performous/performous#174]
I upgraded to windows 10 recently and now getting this after launching:
![image](https://cloud.githubusercontent.com/assets/674200/12076302/1e02488a-b1a6-11e5-9956-34cfca1fa981.png)

I think this is a fairly recent build of performous (less then year).

**Comment by nieknooijens** [comment]
did you install the latest GPU driver?
I had problems in the past with people where the PC manufacturer only installed the directX part of the driver and not the openGL part, resulting in this kind of malfunctioning.

**Comment by nieknooijens** [comment]
closed due to no responce of the reporter.

**Comment by twiecki** [comment]
Sorry, I meant to respond. Thanks for the suggestion, I upgraded the gfx drivers but it didn't affect the problem.

**Comment by twiecki** [comment]
Any other ideas? It's an intel gfx.

**Comment by nieknooijens** [comment]
I just pushed out a new release:
https://github.com/performous/performous/releases/download/1.1/Performous-1.1.exe
![20160123_121003](https://cloud.githubusercontent.com/assets/2794331/12529902/d24a1816-c1ca-11e5-84b9-fc65f4eabfe2.jpg)

our windows machine here has an intel HD4000 and it runs it fine.

**Comment by twiecki** [comment]
@nieknooijens Thanks for letting me know. I tried the version but the problem persists :(.

**Comment by twiecki** [comment]
I gave this another try, installing older and newer drivers but the problem is completely unchanged. Anything else I can try to pinpoint the problem? It happened during the upgrade to Windows 10.

**Comment by twiecki** [comment]
E.g. is there an extra driver I would need for the OpenGL part?

**Comment by Baklap4** [comment]
I'm running perfectly fine on Windows 10 with all recent updates. (Intel HD 4600 Graphics)
What graphics card do you have? and which drivers are installed?
Did you try completely uninstalling the graphics drivers and reinstalling them?

**Comment by twiecki** [comment]
After *downgrading* the gfx driver to the windows 8.1 version it works again. Seems like it's a problem with the custom Yoga 2 driver. Thanks everyone for your help!

**Comment by twiecki** [comment]
Reopening as the 8.1 driver really isn't a stable solution as it gets constantly updated (even if I set it to not auto update). Moreover, no other program has this problem.

**Comment by Baklap4** [comment]
#292 OP's setup:
OS: Windows 10 x64
CPU: Intel i5 5200U
RAM: 8 GByte RAM
GPU: NVidia 940M & Intel HD 5500 (multi GPU device!)
![image](https://user-images.githubusercontent.com/3918517/31197733-4c8ee366-a952-11e7-9da1-57e19e64e6f4.png)

**Comment by Stefan1200-de** [comment]
Another note to the system information posted by @Baklap4 :
The Intel HD Graphics 5500 driver is up to date (20.19.15.4549).

Since my notebook is a multi GPU system, I can set Performous to use the NVidia GPU, which is working fine. But if I can help to test with my Intel HD Graphics 5500 GPU, feel free to ask me. :)

**Comment by Baklap4** [comment]
@Stefan1200-de could you try out this last windows build: https://asgardsings.nl/performous-installer-g4e372338.exe ? Yes the build is very slow (lot's of cpu usage) but that's another issue (#335)

When i tried this, i didn't have a teared / broken screen

**Comment by Stefan1200-de** [comment]
@Baklap4 Well, if I try to run that build with the Intel GPU, I still have that problem followed by a crash of Performous. If I try to run that build with the NVidia 940M GPU, I have a complete freeze of Windows 10, only a hard power cycle is helping to get my Notebook back to work.

**Comment by Baklap4** [comment]
@Stefan1200-de this weekend i'll create a new build of our opengl branch Let's try that one later on

**Comment by Baklap4** [comment]
@Stefan1200-de I've made a windows build on our current openGL branch...

Open GL Branch with current master: https://asgardsings.nl/Performous-1.1-554-opengl-with-master.exe
OpenGL Branch as it currently is: https://asgardsings.nl/Performous-1.1.X-opengl.exe

The one with master in it, can be horribly slow due to #335 
Can you please give these a try?

**Comment by Stefan1200-de** [comment]
**Performous-1.1-554-opengl-with-master.exe**
If I try to run that build with the Intel GPU, I still have that problem followed by a crash of Performous.
If I try to run that build with the NVidia 940M GPU, I have a complete freeze of Windows 10, only a hard power cycle is helping to get my Notebook back to work.

**Performous-1.1.X-opengl.exe**
Runs on NVidia 940M GPU without problem.
Runs on Intel GPU without crashing, but with that displaced graphics like in the screenshots above.

**Comment by Lord-Kamina** [comment]
@Stefan1200-de damn. Could you run the one that doesn't crash with  ```--log debug``` and post the logs?

**Comment by Stefan1200-de** [comment]
@Lord-Kamina **Performous-1.1.X-opengl.exe** with Intel GPU and disturbed / displaced graphics:
[infolog.txt](https://github.com/performous/performous/files/1884653/infolog.txt)

**Comment by Lord-Kamina** [comment]
https://www.dropbox.com/s/ewuk0eak6e153it/Performous-1.1-694-g535f5ee5.exe?dl=1 here's a test build for anybody who might still be reading and interested in this. Note that this revision was built without the webserver and webcam support.

**Comment by Nizhile** [comment]
The test build from 12 July fixed the display problem on my laptop. Thanks

**Comment by Lord-Kamina** [comment]
Great to know. It will take a bit to be merged into master though because it seems somehow it broke display on Linux 🤷🏼‍♂️
