### ISSUE TITLE
An invalid (?) mp3 file can cause memory leak in preview

### ISSUE THREAD

**Issue by jose1711** [performous/performous#444]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I've stumbled upon an mp3 file that causes performous (preview/selection mode) to start eating gigabytes of memory heavily bogging system. Ffplay gives plenty of warnings and skips through the song within a few seconds, mplayer and vlc play it without issues. The actual problem probably lies with ffmpeg but I think performous can handle this in better way (maybe skip with error logged to console).

My system equipped with 8 GB memory eventually recovered but it took no less than 10 minutes.

**Comment by Baklap4** [comment]
Hmmm so that's what causing it.. i encountered this aswell i think last weekend i went to a party, and performous was hogging my memory badly at 60-70%.. way too much

**Comment by Baklap4** [comment]
@jose1711 can you upload this mp3 file here on github so we can try this out ourselves?

**Comment by jose1711** [comment]
@Baklap4 I can share it privately

**Comment by Baklap4** [comment]
Alright hit me up at discord :)

**Comment by Baklap4** [comment]
When playing the file i'm getting a `FfmpegError: code=-1094995529, error=Invalid data found when processing input` from ffmpeg..

**Comment by Baklap4** [comment]
@jose1711 can you provide us again with the mp3? I've lost the one you sent me ages ago..

**Comment by Lord-Kamina** [comment]
BTW I just realized... There is a chance I fixed it already with #507, since I did fix a leak in ffmpeg code.

**Comment by Baklap4** [comment]
Well this certainly isn't fixed, just crashed my system with aubio fixes on master. I'm gonna check with #512 now

**Comment by Baklap4** [comment]
Also not fixed by #512

**Comment by Baklap4** [comment]
Playing this song within vlc player or such does work. @OznOg if i give you the file will you be able to track it down?

**Comment by OznOg** [comment]
```
Thread 73 "performous" hit Breakpoint 6, AudioBuffer::push (this=0x7fff700b4280, data=std::vector of length 2474, capacity 2474 = {...}, timestamp=39867.219689000005)
    at git/performous/game/ffmpeg.cc:104
104                     m_pos = timestamp * m_sps;
(gdb) n
105                     m_data.resize(m_pos, 0);
(gdb) p m_pos
$13 = 3827253090
```
This is way too larg :)

**Comment by Baklap4** [comment]
So it seems once we disable the if statement 
```
void AudioBuffer::push(std::vector<std::int16_t> const& data, double timestamp) {
	std::unique_lock<mutex> l(m_mutex);
	m_cond.wait(l, [this]{ return condition(); });
	if (m_quit) return;
	if (timestamp < 0.0) {
		std::clog << "ffmpeg/warning: Negative audio timestamp " << timestamp << " seconds, frame ignored." << std::endl;
		return;
	}
	// Insert silence at the beginning if the stream starts later than 0.0
	// if (m_pos == 0 && timestamp >= 0.0) {
	// 	m_pos = std::round(float(timestamp * getSamplesPerSecond()));
	// 	if (m_pos % 2 == 1) { m_pos++; timestamp = float(m_pos) / getSamplesPerSecond(); }
	// 	m_data.resize(m_pos, 0);
	// }
	m_data.insert(m_data.end(), data.begin(), data.end());
	m_pos += data.size();
}
```
We're getting an invalid data errorcode `-1094995529` which results in:
`#define AVERROR_INVALIDDATA        FFERRTAG( 'I','N','D','A') ///< Invalid data found when processing input`

This will make the current song skip and go to the next song. @Lord-Kamina you added this into it, you know why we have this if-statement? and inserting lot's of gigs of data?

**Comment by Lord-Kamina** [comment]
I modified that code but didn't add it; here is the commit with the explanation:

https://github.com/performous/performous/pull/507/commits/3013d7d62645c6d572a8aea3c0c86dccd18cb050

Try changing the if back to `>` instead of `>=` maybe?

**Comment by Baklap4** [comment]
Changing it back to `>` still produces the same
Hmm not sure about the order of magnitude but plossible.. :o

**Comment by Lord-Kamina** [comment]
> Changing it back to `>` still produces the same
> Hmm not sure about the order of magnitude but plossible.. :o
> As per ffmpeg warning log it's in order of seconds, or the message might be wrong.. :o
> 
> Dividing timestamp by 1000 does seem to resolve the problem though
> 
> i'm getting the same message as expected:
> 
> ```
> FfmpegError: code=-1094995529, error=Invalid data found when processing input
> ```
> 
> however in the end i got a segfault but not sure if related or not ( i think not)
> 
> ```
> Thread 20 "performous" received signal SIGSEGV, Segmentation fault.
> [Switching to Thread 0x7fffc9458700 (LWP 3548)]
> Music::prepare (this=0x55555cd51f40)
>     at /home/baklap4/repos/performous/performous-master/game/audio.cc:215
> 215					while ((readptr + Audio::aubio_hop_size) <= previewSamples->length) {
> (gdb) bt
> #0  0x00005555556561dc in Music::prepare() (this=0x55555cd51f40)
>     at /home/baklap4/repos/performous/performous-master/game/audio.cc:215
> #1  0x000055555565edf6 in Output::callbackUpdate()
>     (this=this@entry=0x555556006390)
>     at /usr/include/c++/8/bits/unique_ptr.h:356
> #2  0x000055555565f166 in Output::callback(float*, float*, double)
>     (this=0x555556006390, begin=0x7fffac001a10, end=0x7fffac003630, rate=48000)
>     at /home/baklap4/repos/performous/performous-master/game/audio.cc:364
> #3  0x0000555555657315 in Device::operator()(void const*, void*, unsigned long, PaStreamCallbackTimeInfo const*, unsigned long)
>     (this=<optimized out>, input=<optimized out>, output=<optimized out>, frames=<optimized out>)
>     at /home/baklap4/repos/performous/performous-master/game/audio.cc:436
> #4  0x00007ffff30de914 in  () at /lib/x86_64-linux-gnu/libportaudio.so.2
> #5  0x00007ffff30e0924 in  () at /lib/x86_64-linux-gnu/libportaudio.so.2
> #6  0x00007ffff30e97fc in  () at /lib/x86_64-linux-gnu/libportaudio.so.2
> #7  0x00007ffff2671fa3 in start_thread (arg=<optimized out>)
>     at pthread_create.c:486
> #8  0x00007fffee9b94cf in clone ()
>     at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
> ```

If it's in order of seconds then that timestamp is definitely the issue?

**Comment by Baklap4** [comment]
Hmm so the segfault only appears as it is with changing this...

**Comment by OznOg** [comment]
Here it the first "bad" frame the decoder returns:
```
(gdb) p *frame           
$15 = {
  data = {0x7fff3402bd40 "", 0x7fff341334c0 "", 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, 
  linesize = {4608, 0, 0, 0, 0, 0, 0, 0}, 
  extended_data = 0x7fff340cde40, 
  width = 0, 
  height = 0, 
  nb_samples = 1152, 
  format = 8, 
  key_frame = 1, 
  pict_type = AV_PICTURE_TYPE_NONE, 
  sample_aspect_ratio = {
    num = 0, 
    den = 1
  }, 
  pts = 6816223548, 
  pkt_pts = 6816223548, 
  pkt_dts = 6816223548, 
  coded_picture_number = 0, 
  display_picture_number = 0, 
  quality = 0, 
  opaque = 0x0, 
  error = {0, 0, 0, 0, 0, 0, 0, 0}, 
  repeat_pict = 0, 
  interlaced_frame = 0, 
  top_field_first = 0, 
  palette_has_changed = 0, 
  reordered_opaque = -9223372036854775808, 
  sample_rate = 44100, 
  channel_layout = 3, 
  buf = {0x7fff3409acc0, 0x7fff3402d800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, 
  extended_buf = 0x0, 
  nb_extended_buf = 0, 
  side_data = 0x0, 
  nb_side_data = 0, 
  flags = 0, 
  color_range = AVCOL_RANGE_UNSPECIFIED, 
  color_primaries = AVCOL_PRI_RESERVED0, 
  color_trc = AVCOL_TRC_RESERVED0, 
  colorspace = AVCOL_SPC_RGB, 
  chroma_location = AVCHROMA_LOC_UNSPECIFIED, 
  best_effort_timestamp = 6816223548, 
  pkt_pos = -1, 
  pkt_duration = 2351, 
  metadata = 0x0, 
  decode_error_flags = 0, 
  channels = 2, 
--Type <RET> for more, q to quit, c to continue without paging--
  pkt_size = 732, 
  qscale_table = 0x0, 
  qstride = 0, 
  qscale_type = 0, 
  qp_table_buf = 0x0, 
  hw_frames_ctx = 0x0, 
  opaque_ref = 0x0, 
  crop_top = 0, 
  crop_bottom = 0, 
  crop_left = 0, 
  crop_right = 0, 
  private_ref = 0x0
}
```

**Comment by OznOg** [comment]
```
                       if (m_formatContext->start_time != int64_t(AV_NOPTS_VALUE))
                               m_position -= double(m_formatContext->start_time) / AV_TIME_BASE;
```
seems incorrect; shouldn't it be (start time and time_base from stream):
```
                       if (m_formatContext->streams[m_streamId]->start_time != int64_t(AV_NOPTS_VALUE))
                               new_position -= double(m_formatContext->streams[m_streamId]->start_time) * av_q2d(m_formatContext->streams[m_streamId]->time_base);
```

**Comment by OznOg** [comment]
Just for an update: actually, ffplay cannot read the file either, thus we can consider that ffmpeg will not be able to read it either. That said, performous should not missbehave in this case.
The PR #535 thus does not make the file readable for performous, but at least, the code does not crash anymore.
