### ISSUE TITLE
Aubio build failure

### ISSUE THREAD

**Issue by Tronic** [performous/performous#539]
Any quick way to fix this, or to build without?

```
[  1%] Performing build step for 'build-aubio-from-sources'
Setting top to                           : /Users/tronic/Dev/performous/3rdparty/aubio 
Setting out to                           : /Users/tronic/Dev/performous/build/3rdparty/aubio-build 
Checking for 'clang' (C compiler)        : 19:24:46 runner ['/usr/bin/clang', '-dM', '-E', '-']
/usr/bin/clang 
Checking for header stdlib.h             : 19:24:46 runner ['/usr/bin/clang', '-iframeworkwithsysroot', '/System/Library/Frameworks/', '-mmacosx-version-min=', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/', '../test.c', '-c', '-o/Users/tronic/Dev/performous/build/3rdparty/aubio-build/.conf_check_070bd0fc06ee9c62a59527ebb673fa8a/testbuild/test.c.1.o']
not found 
The configuration failed
(complete log in /Users/tronic/Dev/performous/build/3rdparty/aubio-build/config.log)
```

```
# project aubio (0.4.9) configured on Thu Apr 16 19:24:46 2020 by
# waf 2.0.14 (abi 20, python 30707f0 on darwin)
# using /Users/tronic/Dev/performous/3rdparty/aubio/waf --enable-accelerate --disable-tests --notests --verbose --enable-fftw3f --disable-sndfile --disable-avcodec --disable-double --disable-samplerate --disable-docs --disable-wavread --disable-wavwrite --disable-tests --notests --disable-examples --disable-apple-audio --disable-fat --disable-jack --libdir=lib --prefix=/Users/tronic/Dev/performous/build/3rdparty/aubio-install/ --top=/Users/tronic/Dev/performous/3rdparty/aubio/ --out=/Users/tronic/Dev/performous/build/3rdparty/aubio-build/ configure build install
#
----------------------------------------
Setting top to
/Users/tronic/Dev/performous/3rdparty/aubio
----------------------------------------
Setting out to
/Users/tronic/Dev/performous/build/3rdparty/aubio-build
----------------------------------------
Checking for 'clang' (C compiler)
find program=['clang'] paths=['/usr/local/sbin', '/usr/local/opt/curl/bin', '/usr/local/opt/python@3.8/bin', '/usr/local/opt/python@3.6/bin', '/usr/local/bin', '/usr/bin', '/bin', '/usr/sbin', '/sbin', '/Applications/VMware Fusion.app/Contents/Public', '/usr/local/MacGPG2/bin', '/Library/TeX/texbin', '/Applications/Wireshark.app/Contents/MacOS'] var='CC' -> ['/usr/bin/clang']
['/usr/bin/clang', '-dM', '-E', '-']
out: #define OBJC_NEW_PROPERTIES 1
#define _LP64 1
#define __APPLE_CC__ 6000
#define __APPLE__ 1
#define __ATOMIC_ACQUIRE 2
#define __ATOMIC_ACQ_REL 4
#define __ATOMIC_CONSUME 1
#define __ATOMIC_RELAXED 0
#define __ATOMIC_RELEASE 3
#define __ATOMIC_SEQ_CST 5
#define __BIGGEST_ALIGNMENT__ 16
#define __BLOCKS__ 1
#define __BYTE_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __CHAR16_TYPE__ unsigned short
#define __CHAR32_TYPE__ unsigned int
#define __CHAR_BIT__ 8
#define __CLANG_ATOMIC_BOOL_LOCK_FREE 2
#define __CLANG_ATOMIC_CHAR16_T_LOCK_FREE 2
#define __CLANG_ATOMIC_CHAR32_T_LOCK_FREE 2
#define __CLANG_ATOMIC_CHAR_LOCK_FREE 2
#define __CLANG_ATOMIC_INT_LOCK_FREE 2
#define __CLANG_ATOMIC_LLONG_LOCK_FREE 2
#define __CLANG_ATOMIC_LONG_LOCK_FREE 2
#define __CLANG_ATOMIC_POINTER_LOCK_FREE 2
#define __CLANG_ATOMIC_SHORT_LOCK_FREE 2
#define __CLANG_ATOMIC_WCHAR_T_LOCK_FREE 2
#define __CONSTANT_CFSTRINGS__ 1
#define __DBL_DECIMAL_DIG__ 17
#define __DBL_DENORM_MIN__ 4.9406564584124654e-324
#define __DBL_DIG__ 15
#define __DBL_EPSILON__ 2.2204460492503131e-16
#define __DBL_HAS_DENORM__ 1
#define __DBL_HAS_INFINITY__ 1
#define __DBL_HAS_QUIET_NAN__ 1
#define __DBL_MANT_DIG__ 53
#define __DBL_MAX_10_EXP__ 308
#define __DBL_MAX_EXP__ 1024
#define __DBL_MAX__ 1.7976931348623157e+308
#define __DBL_MIN_10_EXP__ (-307)
#define __DBL_MIN_EXP__ (-1021)
#define __DBL_MIN__ 2.2250738585072014e-308
#define __DECIMAL_DIG__ __LDBL_DECIMAL_DIG__
#define __DYNAMIC__ 1
#define __ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__ 101500
#define __FINITE_MATH_ONLY__ 0
#define __FLT16_DECIMAL_DIG__ 5
#define __FLT16_DENORM_MIN__ 5.9604644775390625e-8F16
#define __FLT16_DIG__ 3
#define __FLT16_EPSILON__ 9.765625e-4F16
#define __FLT16_HAS_DENORM__ 1
#define __FLT16_HAS_INFINITY__ 1
#define __FLT16_HAS_QUIET_NAN__ 1
#define __FLT16_MANT_DIG__ 11
#define __FLT16_MAX_10_EXP__ 4
#define __FLT16_MAX_EXP__ 16
#define __FLT16_MAX__ 6.5504e+4F16
#define __FLT16_MIN_10_EXP__ (-4)
#define __FLT16_MIN_EXP__ (-13)
#define __FLT16_MIN__ 6.103515625e-5F16
#define __FLT_DECIMAL_DIG__ 9
#define __FLT_DENORM_MIN__ 1.40129846e-45F
#define __FLT_DIG__ 6
#define __FLT_EPSILON__ 1.19209290e-7F
#define __FLT_EVAL_METHOD__ 0
#define __FLT_HAS_DENORM__ 1
#define __FLT_HAS_INFINITY__ 1
#define __FLT_HAS_QUIET_NAN__ 1
#define __FLT_MANT_DIG__ 24
#define __FLT_MAX_10_EXP__ 38
#define __FLT_MAX_EXP__ 128
#define __FLT_MAX__ 3.40282347e+38F
#define __FLT_MIN_10_EXP__ (-37)
#define __FLT_MIN_EXP__ (-125)
#define __FLT_MIN__ 1.17549435e-38F
#define __FLT_RADIX__ 2
#define __FXSR__ 1
#define __GCC_ASM_FLAG_OUTPUTS__ 1
#define __GCC_ATOMIC_BOOL_LOCK_FREE 2
#define __GCC_ATOMIC_CHAR16_T_LOCK_FREE 2
#define __GCC_ATOMIC_CHAR32_T_LOCK_FREE 2
#define __GCC_ATOMIC_CHAR_LOCK_FREE 2
#define __GCC_ATOMIC_INT_LOCK_FREE 2
#define __GCC_ATOMIC_LLONG_LOCK_FREE 2
#define __GCC_ATOMIC_LONG_LOCK_FREE 2
#define __GCC_ATOMIC_POINTER_LOCK_FREE 2
#define __GCC_ATOMIC_SHORT_LOCK_FREE 2
#define __GCC_ATOMIC_TEST_AND_SET_TRUEVAL 1
#define __GCC_ATOMIC_WCHAR_T_LOCK_FREE 2
#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_1 1
#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_16 1
#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_2 1
#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4 1
#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_8 1
#define __GNUC_MINOR__ 2
#define __GNUC_PATCHLEVEL__ 1
#define __GNUC_STDC_INLINE__ 1
#define __GNUC__ 4
#define __GXX_ABI_VERSION 1002
#define __INT16_C_SUFFIX__ 
#define __INT16_FMTd__ "hd"
#define __INT16_FMTi__ "hi"
#define __INT16_MAX__ 32767
#define __INT16_TYPE__ short
#define __INT32_C_SUFFIX__ 
#define __INT32_FMTd__ "d"
#define __INT32_FMTi__ "i"
#define __INT32_MAX__ 2147483647
#define __INT32_TYPE__ int
#define __INT64_C_SUFFIX__ LL
#define __INT64_FMTd__ "lld"
#define __INT64_FMTi__ "lli"
#define __INT64_MAX__ 9223372036854775807LL
#define __INT64_TYPE__ long long int
#define __INT8_C_SUFFIX__ 
#define __INT8_FMTd__ "hhd"
#define __INT8_FMTi__ "hhi"
#define __INT8_MAX__ 127
#define __INT8_TYPE__ signed char
#define __INTMAX_C_SUFFIX__ L
#define __INTMAX_FMTd__ "ld"
#define __INTMAX_FMTi__ "li"
#define __INTMAX_MAX__ 9223372036854775807L
#define __INTMAX_TYPE__ long int
#define __INTMAX_WIDTH__ 64
#define __INTPTR_FMTd__ "ld"
#define __INTPTR_FMTi__ "li"
#define __INTPTR_MAX__ 9223372036854775807L
#define __INTPTR_TYPE__ long int
#define __INTPTR_WIDTH__ 64
#define __INT_FAST16_FMTd__ "hd"
#define __INT_FAST16_FMTi__ "hi"
#define __INT_FAST16_MAX__ 32767
#define __INT_FAST16_TYPE__ short
#define __INT_FAST32_FMTd__ "d"
#define __INT_FAST32_FMTi__ "i"
#define __INT_FAST32_MAX__ 2147483647
#define __INT_FAST32_TYPE__ int
#define __INT_FAST64_FMTd__ "lld"
#define __INT_FAST64_FMTi__ "lli"
#define __INT_FAST64_MAX__ 9223372036854775807LL
#define __INT_FAST64_TYPE__ long long int
#define __INT_FAST8_FMTd__ "hhd"
#define __INT_FAST8_FMTi__ "hhi"
#define __INT_FAST8_MAX__ 127
#define __INT_FAST8_TYPE__ signed char
#define __INT_LEAST16_FMTd__ "hd"
#define __INT_LEAST16_FMTi__ "hi"
#define __INT_LEAST16_MAX__ 32767
#define __INT_LEAST16_TYPE__ short
#define __INT_LEAST32_FMTd__ "d"
#define __INT_LEAST32_FMTi__ "i"
#define __INT_LEAST32_MAX__ 2147483647
#define __INT_LEAST32_TYPE__ int
#define __INT_LEAST64_FMTd__ "lld"
#define __INT_LEAST64_FMTi__ "lli"
#define __INT_LEAST64_MAX__ 9223372036854775807LL
#define __INT_LEAST64_TYPE__ long long int
#define __INT_LEAST8_FMTd__ "hhd"
#define __INT_LEAST8_FMTi__ "hhi"
#define __INT_LEAST8_MAX__ 127
#define __INT_LEAST8_TYPE__ signed char
#define __INT_MAX__ 2147483647
#define __LDBL_DECIMAL_DIG__ 21
#define __LDBL_DENORM_MIN__ 3.64519953188247460253e-4951L
#define __LDBL_DIG__ 18
#define __LDBL_EPSILON__ 1.08420217248550443401e-19L
#define __LDBL_HAS_DENORM__ 1
#define __LDBL_HAS_INFINITY__ 1
#define __LDBL_HAS_QUIET_NAN__ 1
#define __LDBL_MANT_DIG__ 64
#define __LDBL_MAX_10_EXP__ 4932
#define __LDBL_MAX_EXP__ 16384
#define __LDBL_MAX__ 1.18973149535723176502e+4932L
#define __LDBL_MIN_10_EXP__ (-4931)
#define __LDBL_MIN_EXP__ (-16381)
#define __LDBL_MIN__ 3.36210314311209350626e-4932L
#define __LITTLE_ENDIAN__ 1
#define __LONG_LONG_MAX__ 9223372036854775807LL
#define __LONG_MAX__ 9223372036854775807L
#define __LP64__ 1
#define __MACH__ 1
#define __MMX__ 1
#define __NO_INLINE__ 1
#define __NO_MATH_INLINES 1
#define __OBJC_BOOL_IS_BOOL 0
#define __OPENCL_MEMORY_SCOPE_ALL_SVM_DEVICES 3
#define __OPENCL_MEMORY_SCOPE_DEVICE 2
#define __OPENCL_MEMORY_SCOPE_SUB_GROUP 4
#define __OPENCL_MEMORY_SCOPE_WORK_GROUP 1
#define __OPENCL_MEMORY_SCOPE_WORK_ITEM 0
#define __ORDER_BIG_ENDIAN__ 4321
#define __ORDER_LITTLE_ENDIAN__ 1234
#define __ORDER_PDP_ENDIAN__ 3412
#define __PIC__ 2
#define __POINTER_WIDTH__ 64
#define __PRAGMA_REDEFINE_EXTNAME 1
#define __PTRDIFF_FMTd__ "ld"
#define __PTRDIFF_FMTi__ "li"
#define __PTRDIFF_MAX__ 9223372036854775807L
#define __PTRDIFF_TYPE__ long int
#define __PTRDIFF_WIDTH__ 64
#define __REGISTER_PREFIX__ 
#define __SCHAR_MAX__ 127
#define __SHRT_MAX__ 32767
#define __SIG_ATOMIC_MAX__ 2147483647
#define __SIG_ATOMIC_WIDTH__ 32
#define __SIZEOF_DOUBLE__ 8
#define __SIZEOF_FLOAT__ 4
#define __SIZEOF_INT128__ 16
#define __SIZEOF_INT__ 4
#define __SIZEOF_LONG_DOUBLE__ 16
#define __SIZEOF_LONG_LONG__ 8
#define __SIZEOF_LONG__ 8
#define __SIZEOF_POINTER__ 8
#define __SIZEOF_PTRDIFF_T__ 8
#define __SIZEOF_SHORT__ 2
#define __SIZEOF_SIZE_T__ 8
#define __SIZEOF_WCHAR_T__ 4
#define __SIZEOF_WINT_T__ 4
#define __SIZE_FMTX__ "lX"
#define __SIZE_FMTo__ "lo"
#define __SIZE_FMTu__ "lu"
#define __SIZE_FMTx__ "lx"
#define __SIZE_MAX__ 18446744073709551615UL
#define __SIZE_TYPE__ long unsigned int
#define __SIZE_WIDTH__ 64
#define __SSE2_MATH__ 1
#define __SSE2__ 1
#define __SSE3__ 1
#define __SSE4_1__ 1
#define __SSE_MATH__ 1
#define __SSE__ 1
#define __SSP__ 1
#define __SSSE3__ 1
#define __STDC_HOSTED__ 1
#define __STDC_NO_THREADS__ 1
#define __STDC_UTF_16__ 1
#define __STDC_UTF_32__ 1
#define __STDC_VERSION__ 201112L
#define __STDC__ 1
#define __UINT16_C_SUFFIX__ 
#define __UINT16_FMTX__ "hX"
#define __UINT16_FMTo__ "ho"
#define __UINT16_FMTu__ "hu"
#define __UINT16_FMTx__ "hx"
#define __UINT16_MAX__ 65535
#define __UINT16_TYPE__ unsigned short
#define __UINT32_C_SUFFIX__ U
#define __UINT32_FMTX__ "X"
#define __UINT32_FMTo__ "o"
#define __UINT32_FMTu__ "u"
#define __UINT32_FMTx__ "x"
#define __UINT32_MAX__ 4294967295U
#define __UINT32_TYPE__ unsigned int
#define __UINT64_C_SUFFIX__ ULL
#define __UINT64_FMTX__ "llX"
#define __UINT64_FMTo__ "llo"
#define __UINT64_FMTu__ "llu"
#define __UINT64_FMTx__ "llx"
#define __UINT64_MAX__ 18446744073709551615ULL
#define __UINT64_TYPE__ long long unsigned int
#define __UINT8_C_SUFFIX__ 
#define __UINT8_FMTX__ "hhX"
#define __UINT8_FMTo__ "hho"
#define __UINT8_FMTu__ "hhu"
#define __UINT8_FMTx__ "hhx"
#define __UINT8_MAX__ 255
#define __UINT8_TYPE__ unsigned char
#define __UINTMAX_C_SUFFIX__ UL
#define __UINTMAX_FMTX__ "lX"
#define __UINTMAX_FMTo__ "lo"
#define __UINTMAX_FMTu__ "lu"
#define __UINTMAX_FMTx__ "lx"
#define __UINTMAX_MAX__ 18446744073709551615UL
#define __UINTMAX_TYPE__ long unsigned int
#define __UINTMAX_WIDTH__ 64
#define __UINTPTR_FMTX__ "lX"
#define __UINTPTR_FMTo__ "lo"
#define __UINTPTR_FMTu__ "lu"
#define __UINTPTR_FMTx__ "lx"
#define __UINTPTR_MAX__ 18446744073709551615UL
#define __UINTPTR_TYPE__ long unsigned int
#define __UINTPTR_WIDTH__ 64
#define __UINT_FAST16_FMTX__ "hX"
#define __UINT_FAST16_FMTo__ "ho"
#define __UINT_FAST16_FMTu__ "hu"
#define __UINT_FAST16_FMTx__ "hx"
#define __UINT_FAST16_MAX__ 65535
#define __UINT_FAST16_TYPE__ unsigned short
#define __UINT_FAST32_FMTX__ "X"
#define __UINT_FAST32_FMTo__ "o"
#define __UINT_FAST32_FMTu__ "u"
#define __UINT_FAST32_FMTx__ "x"
#define __UINT_FAST32_MAX__ 4294967295U
#define __UINT_FAST32_TYPE__ unsigned int
#define __UINT_FAST64_FMTX__ "llX"
#define __UINT_FAST64_FMTo__ "llo"
#define __UINT_FAST64_FMTu__ "llu"
#define __UINT_FAST64_FMTx__ "llx"
#define __UINT_FAST64_MAX__ 18446744073709551615ULL
#define __UINT_FAST64_TYPE__ long long unsigned int
#define __UINT_FAST8_FMTX__ "hhX"
#define __UINT_FAST8_FMTo__ "hho"
#define __UINT_FAST8_FMTu__ "hhu"
#define __UINT_FAST8_FMTx__ "hhx"
#define __UINT_FAST8_MAX__ 255
#define __UINT_FAST8_TYPE__ unsigned char
#define __UINT_LEAST16_FMTX__ "hX"
#define __UINT_LEAST16_FMTo__ "ho"
#define __UINT_LEAST16_FMTu__ "hu"
#define __UINT_LEAST16_FMTx__ "hx"
#define __UINT_LEAST16_MAX__ 65535
#define __UINT_LEAST16_TYPE__ unsigned short
#define __UINT_LEAST32_FMTX__ "X"
#define __UINT_LEAST32_FMTo__ "o"
#define __UINT_LEAST32_FMTu__ "u"
#define __UINT_LEAST32_FMTx__ "x"
#define __UINT_LEAST32_MAX__ 4294967295U
#define __UINT_LEAST32_TYPE__ unsigned int
#define __UINT_LEAST64_FMTX__ "llX"
#define __UINT_LEAST64_FMTo__ "llo"
#define __UINT_LEAST64_FMTu__ "llu"
#define __UINT_LEAST64_FMTx__ "llx"
#define __UINT_LEAST64_MAX__ 18446744073709551615ULL
#define __UINT_LEAST64_TYPE__ long long unsigned int
#define __UINT_LEAST8_FMTX__ "hhX"
#define __UINT_LEAST8_FMTo__ "hho"
#define __UINT_LEAST8_FMTu__ "hhu"
#define __UINT_LEAST8_FMTx__ "hhx"
#define __UINT_LEAST8_MAX__ 255
#define __UINT_LEAST8_TYPE__ unsigned char
#define __USER_LABEL_PREFIX__ _
#define __VERSION__ "4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.32.29)"
#define __WCHAR_MAX__ 2147483647
#define __WCHAR_TYPE__ int
#define __WCHAR_WIDTH__ 32
#define __WINT_MAX__ 2147483647
#define __WINT_TYPE__ int
#define __WINT_WIDTH__ 32
#define __amd64 1
#define __amd64__ 1
#define __apple_build_version__ 11030032
#define __block __attribute__((__blocks__(byref)))
#define __clang__ 1
#define __clang_major__ 11
#define __clang_minor__ 0
#define __clang_patchlevel__ 3
#define __clang_version__ "11.0.3 (clang-1103.0.32.29)"
#define __code_model_small_ 1
#define __core2 1
#define __core2__ 1
#define __llvm__ 1
#define __nonnull _Nonnull
#define __null_unspecified _Null_unspecified
#define __nullable _Nullable
#define __pic__ 2
#define __strong 
#define __tune_core2__ 1
#define __unsafe_unretained 
#define __weak __attribute__((objc_gc(weak)))
#define __x86_64 1
#define __x86_64__ 1

find program=['llvm-ar', 'ar'] paths=['/usr/local/sbin', '/usr/local/opt/curl/bin', '/usr/local/opt/python@3.8/bin', '/usr/local/opt/python@3.6/bin', '/usr/local/bin', '/usr/bin', '/bin', '/usr/sbin', '/sbin', '/Applications/VMware Fusion.app/Contents/Public', '/usr/local/MacGPG2/bin', '/Library/TeX/texbin', '/Applications/Wireshark.app/Contents/MacOS'] var='AR' -> ['/usr/bin/ar']
find program=['ar'] paths=['/usr/local/sbin', '/usr/local/opt/curl/bin', '/usr/local/opt/python@3.8/bin', '/usr/local/opt/python@3.6/bin', '/usr/local/bin', '/usr/bin', '/bin', '/usr/sbin', '/sbin', '/Applications/VMware Fusion.app/Contents/Public', '/usr/local/MacGPG2/bin', '/Library/TeX/texbin', '/Applications/Wireshark.app/Contents/MacOS'] var='AR' -> ['/usr/bin/ar']
/usr/bin/clang
----------------------------------------
Checking for header stdlib.h
==>
#include <stdlib.h>

int main(int argc, char **argv) {
	(void)argc; (void)argv;
	return 0;
}

<==
[1/2] Compiling [32m.conf_check_070bd0fc06ee9c62a59527ebb673fa8a/test.c[0m

['/usr/bin/clang', '-iframeworkwithsysroot', '/System/Library/Frameworks/', '-mmacosx-version-min=', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/', '../test.c', '-c', '-o/Users/tronic/Dev/performous/build/3rdparty/aubio-build/.conf_check_070bd0fc06ee9c62a59527ebb673fa8a/testbuild/test.c.1.o']
err: clang: error: invalid version number in '-mmacosx-version-min='

from /Users/tronic/Dev/performous/3rdparty/aubio: Test does not build: Traceback (most recent call last):
  File "/Users/tronic/Dev/performous/3rdparty/aubio/.waf3-2.0.14-43485cf0e38d0acb575a91d747e05f93/waflib/Configure.py", line 325, in run_build
    bld.compile()
  File "/Users/tronic/Dev/performous/3rdparty/aubio/.waf3-2.0.14-43485cf0e38d0acb575a91d747e05f93/waflib/Tools/errcheck.py", line 140, in check_compile
    ret=self.orig_compile()
  File "/Users/tronic/Dev/performous/3rdparty/aubio/.waf3-2.0.14-43485cf0e38d0acb575a91d747e05f93/waflib/Build.py", line 176, in compile
    raise Errors.BuildError(self.producer.error)
waflib.Errors.BuildError: Build failed
 -> task in 'testprog' failed with exit status 1: 
	{task 4427456848: c test.c -> test.c.1.o}
['/usr/bin/clang', '-iframeworkwithsysroot', '/System/Library/Frameworks/', '-mmacosx-version-min=', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/', '../test.c', '-c', '-o/Users/tronic/Dev/performous/build/3rdparty/aubio-build/.conf_check_070bd0fc06ee9c62a59527ebb673fa8a/testbuild/test.c.1.o']

not found
from /Users/tronic/Dev/performous/3rdparty/aubio: The configuration failed
```

**Comment by Lord-Kamina** [comment]
Are you using the script in `osx-utils/`?


The error appears to be the `-mmacosx-version-min` flag is being set to a blank. Try either removing it or setting it to something sensible (a macOS version number in the 10.x format)

**Comment by Tronic** [comment]
Nope, trying normal build with CMake by hand. The script fails with
```
-- Found AVUtil 
CMake Error at cmake/Modules/FindAVCodec.cmake:36 (message):
  Found avcodec.h include dir, but not the header file.  Perhaps you need to
  clear CMake cache?
Call Stack (most recent call first):
  cmake/Modules/LibFindMacros.cmake:14 (find_package)
  cmake/Modules/FindAVFormat.cmake:14 (libfind_package)
  game/CMakeLists.txt:89 (find_package)
```

The normal CMake build worked fine until recently.

**Comment by Baklap4** [comment]
https://github.com/aubio/aubio/issues/285#issuecomment-614081074 check this out

**Comment by Tronic** [comment]
I used some older random commit for now. It might be a good idea to make aubio an optional feature, or get the build scripts fixed so that they work on all systems out of the box.

**Comment by Lord-Kamina** [comment]
> Nope, trying normal build with CMake by hand. The script fails with
> 
> ```
> -- Found AVUtil 
> CMake Error at cmake/Modules/FindAVCodec.cmake:36 (message):
>   Found avcodec.h include dir, but not the header file.  Perhaps you need to
>   clear CMake cache?
> Call Stack (most recent call first):
>   cmake/Modules/LibFindMacros.cmake:14 (find_package)
>   cmake/Modules/FindAVFormat.cmake:14 (libfind_package)
>   game/CMakeLists.txt:89 (find_package)
> ```
> 
> The normal CMake build worked fine until recently.

And you're using Homebrew, right? The script on master should work if you try invoking it using 
`PREFIXDIR="/usr/local" ./performous-app-build.sh -D` (or wherever your homebrew install is actually at).

Please let me know if it works that way.

Anyway, it seems the specific bug you encountered was introduced by the recent change to have CMake directly invoke wad to build audio. Precisely, here:

https://github.com/performous/performous/blob/39dad10cc289d2eb6e73cba300ae0602fd718048/CMakeLists.txt#L78-L82

That of course needs to be fixed, but it should be self-evident what you need to do to fix it.

**Comment by Tronic** [comment]
> And you're using Homebrew, right? The script on master should work if you try invoking it using
PREFIXDIR="/usr/local" ./performous-app-build.sh -D (or wherever your homebrew install is actually at).

Same error. And yes, I'm using Homebrew, but the script sets `-DAVCodec_INCLUDE_DIR=/opt/local/include/libavcodec`. I don't think I ever used Macports, and not even `/opt/local` exists. Why the script, instead of letting CMake find the libs?

**Comment by Tronic** [comment]
With current master and with manually specified `PREFIX_DIR` it proceeds until linking (possibly I was on an earlier commit with the previous error):
```
make[2]: *** No rule to make target `/usr/local/lib/libxml2.dylib', needed by `performous'.  Stop.
```

Looks like I've got `/usr/lib/libxml2.dylib` (shipped with Catalina?) that presumably should be used with Homebrew's libxml++.  In general it would be better to let CMake find the files, or to provide `CMAKE_PREFIX_PATH` instead of forcing all paths from an external script, especially since this method ends up pointing to paths that don't exist.

**Comment by Lord-Kamina** [comment]
> With current master and with manually specified `PREFIX_DIR` it proceeds until linking (possibly I was on an earlier commit with the previous error):
> 
> ```
> make[2]: *** No rule to make target `/usr/local/lib/libxml2.dylib', needed by `performous'.  Stop.
> ```
> 
> Looks like I've got `/usr/lib/libxml2.dylib` (shipped with Catalina?) that presumably should be used with Homebrew's libxml++. In general it would be better to let CMake find the files, or to provide `CMAKE_PREFIX_PATH` instead of forcing all paths from an external script, especially since this method ends up pointing to paths that don't exist.

That is fixed in an already existing PR; nonetheless, I strongly recommend using the least amount of system components possible. In the case of Macports at least, linking against system libraries most offen produces linking errors although Homebrew might be different.

**Comment by Baklap4** [comment]
This issue seems to have resolved itself with the latest changes on master. Anyone who can verify. If not resolved please reopen the issue
